### ISSUE TITLE
Copying mod... failed!

### ISSUE THREAD

**Issue by Prem-is-bored** [Idhrendur/paradoxGameConverters#174] opened 2016-12-10 21:31 UTC
There is an issue with copying the mod that you make when converting an EU4 save to Vic2.

Here is what the log says
```
2016-12-10 21:24:48   [DEBUG]     Army 1st Fleet has no regiments after conversion; skipping
2016-12-10 21:24:49   [DEBUG]     Army 2nd Fleet has no regiments after conversion; skipping
2016-12-10 21:24:49   [DEBUG]     Writing diplomacy
2016-12-10 21:24:49   [DEBUG]     Writing pops
2016-12-10 21:24:50    [INFO] * Conversion complete *
```

After that, it just crashes...

**Comment by Idhrendur** [comment] 2016-12-10 21:45
Can you share you configuration.txt and the full log.txt from the converter directory?

**Comment by Prem-is-bored** [comment] 2016-12-10 21:56
Will do when I get my computer fixed (I messed it up just now -_-)

**Comment by Prem-is-bored** [comment] 2016-12-11 09:25
Okay, so here is the configuration.txt file:
configuration =
```
{
	# Europa Universalis 4 directory: A path on your computer where Europa Universalis 4 is installed
	EU4directory = "C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis IV"

	# EU4 Documents Directory: A path on your computer where Europa Universalis 4 keeps temporary files
	EU4DocumentsDirectory = "C:\Users\szlig\Documents\Paradox Interactive\Europa Universalis IV"

	# CK2 Export Directory: A path on your computer where Crusader Kings 2 keeps exported games
	CK2ExportDirectory = ""

	# Victoria 2 directory: A path on your computer where Victoria 2 is installed
	V2directory = "C:\Program Files (x86)\Steam\steamapps\common\Victoria 2"

	# Victoria 2 Documents directory: A path on your computer where Victoria 2 keeps temporary files
	V2Documentsdirectory = "C:\Users\szlig\Documents\Paradox Interactive\Victoria II"

	# V2 Game Version: V2 Game Version: what version of V2 to convert to
	#	Heart of Darkness (3.x)	 - Heart of Darkness (3.x)
	V2gametype = "HOD"

	# Max Literacy: The maximum literacy a nation will start with. Default 100%
	max_literacy = "1"

	# Types of Landless nations to remove: Which landless nations to remove
	#	None	 - Remove none of them
	#	Dead	 - Remove ones without cultural backing
	#	All	 - Remove all of them
	Removetype = "none"

	# Liberty threshold: The threshold value for when colonies are not absorbed. Default 100% (colonies always absorbed)
	libertyThreshold = "100"

	# Convert pop totals?: Whether or not the population totals should be converted.
	#	Yes	 - The population totals should be converted
	#	No	 - The population totals should NOT be converted
	convertPopTotals = "no"

}
```

Here is the log.txt file after running a vanilla game as the Ottomans for a month (i have character limitations to 65536, so I have only inserted areas with an error in them. gaps between errors are defined with a new paragraph):

```
2016-12-11 09:03:35    [INFO] Converter version 1.0C
2016-12-11 09:03:35    [INFO] Built Sat Nov 19 10:29:36 2016
2016-12-11 09:03:35   [DEBUG]     Current directory is C:\Users\szlig\Desktop\eu4 vic2\eu4tovic2
2016-12-11 09:03:35    [INFO] Using input file C:\Users\szlig\Desktop\eu4 vic2\Rise of the Ottomans 1.19.2.eu4
2016-12-11 09:03:35    [INFO] Reading configuration file
2016-12-11 09:03:35   [DEBUG]     EU4 install path is C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis IV
2016-12-11 09:03:35   [DEBUG]     Victoria 2 install path is C:\Program Files (x86)\Steam\steamapps\common\Victoria 2
2016-12-11 09:03:35   [DEBUG]     Victoria 2 documents directory is C:\Users\szlig\Documents\Paradox Interactive\Victoria II
2016-12-11 09:03:35    [INFO] Using output name Rise_of_the_Ottomans_1
2016-12-11 09:03:35   [DEBUG]     Get EU4 Mod Directory
2016-12-11 09:03:35   [DEBUG]     EU4 Documents directory is C:\Users\szlig\Documents\Paradox Interactive\Europa Universalis IV
2016-12-11 09:03:36   [DEBUG]     Get CK2 Export Directory
2016-12-11 09:03:36   [DEBUG]     CK2 export directory is 
2016-12-11 09:03:36    [INFO] * Importing EU4 save *
2016-12-11 09:03:36    [INFO] Parsing save
2016-12-11 09:03:47   [DEBUG]     Get EU4 Mod
2016-12-11 09:03:47    [INFO] Building world
2016-12-11 09:03:48    [INFO] Sum of all Province Weights: 22392.4
2016-12-11 09:03:48    [INFO] World Tag Map Size: 414
2016-12-11 09:03:48    [INFO] Parsing culture mappings
2016-12-11 09:03:48 [WARNING] No culture mapping for EU4 culture afar
2016-12-11 09:03:48    [INFO] Parsing EU4 regions
2016-12-11 09:03:48 [WARNING] Clearing stack size 3 - this should not happen in normal operation
brittany_area=
{
	color={"118" "99" "151" }
}

169=
{
}

169=
{
}


2016-12-11 09:03:48 [WARNING] No culture mapping for EU4 culture beja
2016-12-11 09:03:48 [WARNING] No culture mapping for EU4 culture harari
2016-12-11 09:03:48 [WARNING] No culture mapping for EU4 culture oromo
2016-12-11 09:03:48    [INFO] Reading EU4 common/countries
2016-12-11 09:03:56 [WARNING] Clearing stack size 3 - this should not happen in normal operation
monarch_names=
{
	Opothleyaholo #0=20
	Emistesigo #0=10
	Fife #0=10
	Hoboi-Hili-Miko #0=10
	Lamochattee #0=20
	Yahatatastenake #0=20
}

Taskanugi Hatke=
{
}

Taskanugi Hatke=
{
}


2016-12-11 09:04:07    [INFO] Reading localisation
2016-12-11 09:04:16    [INFO] Resolving unit types.
2016-12-11 09:04:16    [INFO] 	Reading unit strengths from EU4 installation folder
2016-12-11 09:04:19    [INFO] Merging nations
2016-12-11 09:04:19    [INFO] Parsing province mappings
2016-12-11 09:04:19   [DEBUG]     Using version 1.16.0.0 mappings
2016-12-11 09:04:19 [WARNING] No mapping for province 4141
2016-12-11 09:04:19 [WARNING] No mapping for province 4142
2016-12-11 09:04:19 [WARNING] No mapping for province 4143
2016-12-11 09:04:19 [WARNING] No mapping for province 4144
2016-12-11 09:04:19 [WARNING] No mapping for province 4145
2016-12-11 09:04:19 [WARNING] No mapping for province 4146
2016-12-11 09:04:19 [WARNING] No mapping for province 4147
2016-12-11 09:04:19 [WARNING] No mapping for province 4148
2016-12-11 09:04:19 [WARNING] No mapping for province 4149
2016-12-11 09:04:19 [WARNING] No mapping for province 4150
2016-12-11 09:04:19 [WARNING] No mapping for province 4151
2016-12-11 09:04:19 [WARNING] No mapping for province 4152
2016-12-11 09:04:19 [WARNING] No mapping for province 4153
2016-12-11 09:04:19 [WARNING] No mapping for province 4154
2016-12-11 09:04:19 [WARNING] No mapping for province 4155
2016-12-11 09:04:19 [WARNING] No mapping for province 4156
2016-12-11 09:04:19 [WARNING] No mapping for province 4157
2016-12-11 09:04:19 [WARNING] No mapping for province 4158
2016-12-11 09:04:19 [WARNING] No mapping for province 4159
2016-12-11 09:04:19 [WARNING] No mapping for province 4160
2016-12-11 09:04:19 [WARNING] No mapping for province 4161
2016-12-11 09:04:19 [WARNING] No mapping for province 4162
2016-12-11 09:04:19 [WARNING] No mapping for province 4163
2016-12-11 09:04:19 [WARNING] No mapping for province 4164
2016-12-11 09:04:19 [WARNING] No mapping for province 4165
2016-12-11 09:04:19 [WARNING] No mapping for province 4166
2016-12-11 09:04:19 [WARNING] No mapping for province 4167
2016-12-11 09:04:19 [WARNING] No mapping for province 4168
2016-12-11 09:04:19 [WARNING] No mapping for province 4169
2016-12-11 09:04:19 [WARNING] No mapping for province 4170
2016-12-11 09:04:19 [WARNING] No mapping for province 4171
2016-12-11 09:04:19 [WARNING] No mapping for province 4172
2016-12-11 09:04:19 [WARNING] No mapping for province 4173
2016-12-11 09:04:19 [WARNING] No mapping for province 4174
2016-12-11 09:04:19 [WARNING] No mapping for province 4175
2016-12-11 09:04:19 [WARNING] No mapping for province 4176
2016-12-11 09:04:19 [WARNING] No mapping for province 4177
2016-12-11 09:04:19 [WARNING] No mapping for province 4178
2016-12-11 09:04:19 [WARNING] No mapping for province 4179
2016-12-11 09:04:19    [INFO] Parsing EU4 religions
2016-12-11 09:04:19    [INFO] Parsing religion mappings
2016-12-11 09:04:19   [DEBUG]     Removing empty nation ADU
2016-12-11 09:04:19   [DEBUG]     Removing empty nation ARB
2016-12-11 09:04:19   [DEBUG]     Removing empty nation ASA

2016-12-11 09:05:16   [DEBUG]     DTE ruling party is DTE_liberal
2016-12-11 09:05:16   [DEBUG]     Setting literacy for DTE to 0.01
2016-12-11 09:05:16   [DEBUG]     DTE has tech school traditional_academic
2016-12-11 09:05:16 [WARNING] No government mapping defined for peasants_republic
2016-12-11 09:05:16   [DEBUG]     X13 has an Upper House of 5 reactionary, 85 conservative, and 10 liberal
2016-12-11 09:05:16   [DEBUG]     X13 ruling party is X13_liberal
2016-12-11 09:05:16 [WARNING] Undefined government type '' while setting reforms for X13
2016-12-11 09:05:16 [WARNING] Undefined government type '' while setting reforms for X13
2016-12-11 09:05:16   [DEBUG]     Setting literacy for X13 to 0.1
2016-12-11 09:05:16   [DEBUG]     X13 has tech school traditional_academic
2016-12-11 09:05:16   [DEBUG]     DUL has an Upper House of 5 reactionary, 85 conservative, and 10 liberal

2016-12-11 09:05:16   [DEBUG]     X15 ruling party is X15_liberal
2016-12-11 09:05:16   [DEBUG]     Setting literacy for X15 to 0.1
2016-12-11 09:05:16   [DEBUG]     X15 has tech school traditional_academic
2016-12-11 09:05:16 [WARNING] No culture mapping defined for harari (ETH -> ETH)
2016-12-11 09:05:16 [WARNING] No culture mapping defined for afar (ETH -> ETH)
2016-12-11 09:05:16 [WARNING] No culture mapping defined for oromo (ETH -> ETH)
2016-12-11 09:05:16   [DEBUG]     ETH has an Upper House of 5 reactionary, 85 conservative, and 10 liberal
2016-12-11 09:05:16   [DEBUG]     ETH ruling party is ETH_liberal
2016-12-11 09:05:16   [DEBUG]     Setting literacy for ETH to 0.01
2016-12-11 09:05:16   [DEBUG]     ETH has tech school traditional_academic
2016-12-11 09:05:16   [DEBUG]     FEO has an Upper House of 5 reactionary, 85 conservative, and 10 liberal

2016-12-11 09:05:17   [DEBUG]     SIN ruling party is SIN_liberal
2016-12-11 09:05:17   [DEBUG]     Setting literacy for SIN to 0.01
2016-12-11 09:05:17   [DEBUG]     SIN has tech school traditional_academic
2016-12-11 09:05:17 [WARNING] No culture mapping defined for harari (SOA -> X53)
2016-12-11 09:05:17 [WARNING] No culture mapping defined for afar (SOA -> X53)
2016-12-11 09:05:17 [WARNING] No culture mapping defined for oromo (SOA -> X53)
2016-12-11 09:05:17   [DEBUG]     X53 has an Upper House of 5 reactionary, 85 conservative, and 10 liberal

2016-12-11 09:05:18   [DEBUG]     ZAP had 1 prestige
2016-12-11 09:05:18   [DEBUG]     ZAZ had 1 prestige
2016-12-11 09:05:18   [DEBUG]     ZIM had 1 prestige
2016-12-11 09:05:18   [DEBUG]     ZZZ had 1 prestige
2016-12-11 09:05:25    [INFO] Converting provinces
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1771
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1829
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1833
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1834
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1836
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1851
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1858
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1858
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1865
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1865
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1866
2016-12-11 09:05:25 [WARNING] Could not set culture for pops in Vic2 province 1875
2016-12-11 09:05:26    [INFO] Converting diplomacy
2016-12-11 09:05:26   [DEBUG]     	POL is absorbing MOL
2016-12-11 09:05:26    [INFO] Setting colonies
2016-12-11 09:05:26    [INFO] Importing province adjacencies
2016-12-11 09:05:26 [WARNING] Could not find C:\Users\szlig\Documents\Paradox Interactive\Victoria II/map/cache/adjacencies.bin - looking in install folder
2016-12-11 09:05:26    [INFO] Finding Continents
2016-12-11 09:05:27    [INFO] Creating states
2016-12-11 09:05:27    [INFO] Parsing region structure

2016-12-11 09:05:27    [INFO] Adding unions
2016-12-11 09:05:27    [INFO] Converting armies and navies
2016-12-11 09:05:27 [WARNING] V2 province 1867 is home for a ADA cavalry regiment, but belongs to MRE - dissolving regiment to pool
2016-12-11 09:05:27   [DEBUG]     Army/navy 1st Army has no valid home provinces for cavalry due to previous errors; dissolving to pool
2016-12-11 09:05:27   [DEBUG]     Disqualifying army/navy 1st Army from receiving more cavalry from the pool
2016-12-11 09:05:27   [DEBUG]     No suitable army or navy found for ADA's pooled regiments of cavalry
2016-12-11 09:05:27 [WARNING] V2 province 1258 is home for a ASS infantry regiment, but belongs to KMT - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] V2 province 1339 is home for a AVA infantry regiment, but belongs to MYA - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] V2 province 2176 is home for a AZT infantry regiment, but belongs to TLX - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] V2 province 2173 is home for a AZT infantry regiment, but belongs to TOT - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] Navy 2nd Fleet assigned to EU4 province 1744 which has no corresponding V2 port provinces; dissolving to pool
2016-12-11 09:05:27   [DEBUG]     No suitable army or navy found for BRB's pooled regiments of light_ship
2016-12-11 09:05:27   [DEBUG]     No suitable army or navy found for BRB's pooled regiments of transport
2016-12-11 09:05:27 [WARNING] V2 province 192 is home for a CHO infantry regiment, but belongs to  - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] V2 province 1049 is home for a CIR infantry regiment, but belongs to GNA - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] V2 province 2310 is home for a CLA infantry regiment, but belongs to CRA - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] V2 province 2314 is home for a CRA infantry regiment, but belongs to PCJ - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] V2 province 1050 is home for a CRI infantry regiment, but belongs to GOL - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] V2 province 195 is home for a CRK infantry regiment, but belongs to  - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] infantry unit in army/navy 1st Army has unmapped home province 4149 - dissolving to pool
2016-12-11 09:05:27 [WARNING] V2 province 1239 is home for a DLH cavalry regiment, but belongs to JNP - dissolving regiment to pool
2016-12-11 09:05:27 [WARNING] Navy Royal Navy assigned to EU4 province 236 which has no corresponding V2 port provinces; dissolving to pool
2016-12-11 09:05:27   [DEBUG]     No suitable army or navy found for ENL's pooled regiments of heavy_ship
2016-12-11 09:05:27   [DEBUG]     No suitable army or navy found for ENL's pooled regiments of light_ship
2016-12-11 09:05:27   [DEBUG]     No suitable army or navy found for ENL's pooled regiments of transport
2016-12-11 09:05:27 [WARNING] V2 province 1305 is home for a GRJ infantry regiment, but belongs to ORI - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 2182 is home for a KIC infantry regiment, but belongs to ZAP - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1252 is home for a KMT cavalry regiment, but belongs to BNG - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy 1st Army has no valid home provinces for cavalry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy 1st Army from receiving more cavalry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for KMT's pooled regiments of cavalry
2016-12-11 09:05:28 [WARNING] V2 province 1534 is home for a KRC cavalry regiment, but belongs to KHA - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1613 is home for a KRC cavalry regiment, but belongs to MNG - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy Kheshig has no valid home provinces for cavalry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy Kheshig from receiving more cavalry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for KRC's pooled regiments of cavalry
2016-12-11 09:05:28 [WARNING] V2 province 715 is home for a LIT cavalry regiment, but belongs to POL - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1552 is home for a MHX cavalry regiment, but belongs to KRC - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1938 is home for a MSI infantry regiment, but belongs to OYO - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1804 is home for a MSI infantry regiment, but belongs to JNN - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] Navy 2nd Fleet assigned to EU4 province 210 which has no corresponding V2 port provinces; dissolving to pool
2016-12-11 09:05:28 [WARNING] Navy 1st Fleet assigned to EU4 province 210 which has no corresponding V2 port provinces; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for NAV's pooled regiments of light_ship
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for NAV's pooled regiments of transport
2016-12-11 09:05:28 [WARNING] V2 province 430 is home for a NEV infantry regiment, but belongs to FRA - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy Armée du Nivernais has no valid home provinces for infantry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy Armée du Nivernais from receiving more infantry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for NEV's pooled regiments of infantry
2016-12-11 09:05:28   [DEBUG]     Army/navy Armée du Nivernais has no valid home provinces for cavalry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy Armée du Nivernais from receiving more cavalry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for NEV's pooled regiments of cavalry
2016-12-11 09:05:28 [WARNING] V2 province 1248 is home for a NGP infantry regiment, but belongs to JNP - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1940 is home for a NUP cavalry regiment, but belongs to ZZZ - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy 1st Army has no valid home provinces for cavalry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy 1st Army from receiving more cavalry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for NUP's pooled regiments of cavalry
2016-12-11 09:05:28 [WARNING] V2 province 1466 is home for a OIR cavalry regiment, but belongs to KHA - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1641 is home for a OUC cavalry regiment, but belongs to YMN - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy Ouchi Gun has no valid home provinces for cavalry due to previous errors; dissolving to pool

2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for PRM's pooled regiments of cavalry
2016-12-11 09:05:28 [WARNING] V2 province 1401 is home for a SAK cavalry regiment, but belongs to PSA - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy 1st Army has no valid home provinces for cavalry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy 1st Army from receiving more cavalry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for SAK's pooled regiments of cavalry
2016-12-11 09:05:28 [WARNING] Army or Navy 1st Army assigned to unmapped province 4176; dissolving to pool
2016-12-11 09:05:28 [WARNING] transport unit in army/navy 1st Fleet has unmapped home province 4176 - dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy 1st Fleet has no valid home provinces for transport due to previous errors; dissolving to pool

2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for SER's pooled regiments of galley
2016-12-11 09:05:28   [DEBUG]     Army/navy 1st Fleet has no valid home provinces for transport due to previous errors; dissolving to pool

2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy 1st Fleet from receiving more transport from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for SER's pooled regiments of transport
2016-12-11 09:05:28 [WARNING] V2 province 1159 is home for a SHM infantry regiment, but belongs to NEJ - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1588 is home for a UTS infantry regiment, but belongs to KAM - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1588 is home for a UTS infantry regiment, but belongs to KAM - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1872 is home for a WAR infantry regiment, but belongs to MRE - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 2118 is home for a X06 infantry regiment, but belongs to X01 - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 2266 is home for a X09 infantry regiment, but belongs to  - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy 1st Army has no valid home provinces for infantry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy 1st Army from receiving more infantry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for X09's pooled regiments of infantry
2016-12-11 09:05:28 [WARNING] V2 province 1985 is home for a X62 cavalry regiment, but belongs to KON - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy 1st Army has no valid home provinces for cavalry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy 1st Army from receiving more cavalry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for X62's pooled regiments of cavalry
2016-12-11 09:05:28 [WARNING] V2 province 1803 is home for a ZAF infantry regiment, but belongs to TMB - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1804 is home for a ZAF infantry regiment, but belongs to JNN - dissolving regiment to pool
2016-12-11 09:05:28 [WARNING] V2 province 1948 is home for a ZZZ cavalry regiment, but belongs to KTS - dissolving regiment to pool
2016-12-11 09:05:28   [DEBUG]     Army/navy 1st Army has no valid home provinces for cavalry due to previous errors; dissolving to pool
2016-12-11 09:05:28   [DEBUG]     Disqualifying army/navy 1st Army from receiving more cavalry from the pool
2016-12-11 09:05:28   [DEBUG]     No suitable army or navy found for ZZZ's pooled regiments of cavalry

2016-12-11 09:08:09   [DEBUG]     Copying flags
2016-12-11 09:08:17   [DEBUG]     Writing localisation text
2016-12-11 09:08:17   [DEBUG]     It's not a random world
2016-12-11 09:08:17   [DEBUG]     Writing provinces
2016-12-11 09:08:51   [DEBUG]     Writing countries
2016-12-11 09:09:10   [DEBUG]     Writing diplomacy
2016-12-11 09:09:10   [DEBUG]     Writing pops
2016-12-11 09:09:12    [INFO] * Conversion complete *
```

I will also try converting a game with my CKII export directory mentioned as well to see if there are any differences...

**Comment by Prem-is-bored** [comment] 2016-12-11 13:58
@Idhrendur 
CORRECTION:
The converter has a few issues with making long names for saves.
My file "Rise_of_the_Ottomans_1.19.2" was shortened to "Rise_of_the_Ottomans_1", therefore the converter "panicked" due to the lack of the ".19.2" in the file, thinking it is a completely new mod.

**Comment by Idhrendur** [comment] 2017-01-02 03:59
Good catch for the cause. The converter trimmed extensions starting at the first period, and the frontend did so using the last period (I think, there's actually a standard function for that in C#). It should be fixed next release.

**Closed by Idhrendur** 2017-01-02 03:59 UTC
Labels: bug, EU4ToVic2
