### ISSUE TITLE
Custom countries get incorrect cultures on conversion

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#217] opened 2017-02-05 15:55 UTC
See here:

https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-16#post-22368963
https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-16#post-22371330

**Comment by kratostatic** [comment] 2017-06-02 17:41
The save given by the user who made note of the issue is Ironman and I don't know what version of EU4 it was saved in.  

More to the point, I think that this is a save converted directly from the 1444 start and so the culture conversion won't have happened yet as far as the converter is concerned.  I'm going to consider this a corner case and provisionally close the issue.  

I will be adding a "literal" culture conversion option in future as well which would deal with this kind of problem.

**Closed by kratostatic** 2017-06-02 17:41 UTC
Labels: bug, EU4ToVic2
