### ISSUE TITLE
Investigate another crash

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#227] opened 2017-02-14 03:00 UTC
https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-17#post-22412082
https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-17#post-22415841
https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-17#post-22418084
https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-18#post-22424051

**Comment by derHochmeister** [comment] 2017-06-06 18:35
What do they say? (Can't see forums, if I knew problem, I may find solution)

**Comment by Idhrendur** [comment] 2017-06-06 21:43
It's a screenshot of the frontend saying it failed, then an attached log file, then an attached save, then the different mods used. Nothing easily taken off the forums. :-(

**Comment by derHochmeister** [comment] 2017-06-07 13:34
Maybe they should try the latest converter or a modless conversion.

**Comment by kratostatic** [comment] 2017-07-05 17:00
Yeah I'm going to close this, as looking at the mods they used their updates are all over the place.  Plus this is sufficiently long ago that either the problem is fixed or we'll be better off fixing the next time it comes up.

**Closed by kratostatic** 2017-07-05 17:00 UTC
Labels: Crash Investigation, EU4ToVic2
